######################################################################
# Automatically generated by qmake (3.0) jeu. mai 31 16:18:51 2018
######################################################################

TEMPLATE = app
TARGET = code
INCLUDEPATH += .

QT += sql
QT += widgets

# Input
HEADERS += Mainwindow.hpp remplissage_bdd.hpp
SOURCES += main.cpp Mainwindow.cpp remplissage_bdd.cpp
